version: "3"
services:
    frontend:
        image: ghcr.io/chicky0/front-end:latest
        container_name: frontend
        ports: 
            - "8080:8080"

networks:
    default:
        eventmod-network:
            external: true