version: "3"
services:
    frontend:
        image: frontend:latest
        container_name: frontend
        ports: 
            - "8080:8080"

networks:
    default:
        external:
            name: eventmod