version: "3.1"
services:
    frontend:
        container_name: frontend
        build: .
        image: ghcr.io/chicky0/eventmod-frontend:latest
        ports: 
            - "8080:8080"

networks:
    default:
        external:
            name: eventmod-network