version: "3.1"
services:
    frontend-prd:
        container_name: frontend-prd
        build: .
        image: ghcr.io/eventmod/eventmod-frontend:prd
        env_file:
            - ./.env.prd
        ports: 
            - "8080:8080"

networks:
    default:
        external:
            name: eventmod-network