version: "3"
services:
    frontend-dev:
        container_name: frontend-dev
        build: .
        image: ghcr.io/eventmod/eventmod-frontend:dev
        env_file:
            - ./.env.development
        ports: 
            - "8081:8081"

networks:
    default:
        external:
            name: eventmod-network