version: "3.1"
services:
    frontend:
        container_name: frontend-dev
        build: .
        image: ghcr.io/eventmod/eventmod-frontend:dev
        ports: 
            - "8081:8080"

networks:
    default:
        external:
            name: eventmod-network